/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.quadrillenschule.azocamsyncd.astromode_old.gui;

import de.quadrillenschule.azocamsyncd.astromode_old.ReceivePhotoSerie;

/**
 *
 * @author Andreas
 */
public class WaitingForFilesJDialog extends javax.swing.JDialog {
    
    PhotoProjectJPanel ppj;

    /**
     * Creates new form WaitingForFilesJDialog
     */
    public WaitingForFilesJDialog(java.awt.Frame parent, PhotoProjectJPanel ppj) {
        super(parent, true);
        this.ppj = ppj;
        initComponents();
    }
    
    public void update(ReceivePhotoSerie ps) {
        projectjLabel.setText(ppj.getProject().getName());
        seriesjLabel.setText(ps.getName()+": Waiting for "+(ps.getPhotos().size()+1)+" from "+ps.getNumberOfPlannedPhotos()+" files");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        projectjLabel = new javax.swing.JLabel();
        seriesjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Waiting for files...");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        projectjLabel.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(projectjLabel, gridBagConstraints);

        seriesjLabel.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(seriesjLabel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel projectjLabel;
    private javax.swing.JLabel seriesjLabel;
    // End of variables declaration//GEN-END:variables
}
